### ISSUE TITLE
Install Failure

### ISSUE THREAD

**Issue by nitrousdigital** [danmarshall/tsx-create-element#14]
Hi @danmarshall ,
I'm having issues installing tsx-create-element@2.2.4:

```
> tsx-create-element@2.2.4 preinstall D:\work\icg\workspace\lux-sanddance\node_modules\tsx-create-element
> npx npm-force-resolutions

npx: installed 5 in 1.448s
ENOENT: no such file or directory, open './package-lock.json'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tsx-create-element@2.2.4 preinstall: `npx npm-force-resolutions`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tsx-create-element@2.2.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Apparently this might be caused by the recently added line in package.json: `preinstall: "npx npm-force-resolutions"`

See https://github.com/oktadeveloper/schematics/issues/192#issuecomment-688720326

**Comment by danmarshall** [comment]
Hello @nitrousdigital , thanks for reporting. I do have [package-lock.json](https://github.com/danmarshall/tsx-create-element/blob/master/package-lock.json) in the repo, is it not in your `node_modules/tsx-create-element` folder?

**Comment by danmarshall** [comment]
Found related issues: 
https://github.com/rogeriochaves/npm-force-resolutions/issues/10
https://github.com/rogeriochaves/npm-force-resolutions/issues/12

Probably, I only need this for dev. I will undo it for `preinstall`.

**Comment by danmarshall** [comment]
Thank you for filing. Please try version 2.2.5

**Comment by nitrousdigital** [comment]
Thanks Dan, 
Version 2.2.5 installed without issues.

I did not have the node_modules\tsx-create-element folder prior to installation and since the installation was failing, the folder was getting removed before I could examine it to check for the presence of the package-lock.json.

Thanks for your quick fix!
