### ISSUE TITLE
Usage in tests?

### ISSUE THREAD

**Issue by NickDarvey** [danmarshall/tsx-create-element#18]
Hi,

I see this package being referenced in [the SandDance repo](https://github.com/microsoft/SandDance/blob/a0125eebf583e0092e9d615b22b4dd4a256ca8d1/packages/vega-deck.gl/test/tsconfig.json#L5) but not being used.

I have a similar use case for it. Do you know of anywhere this being used with Jest by any chance?

**Comment by danmarshall** [comment]
Hi @NickDarvey , it is being used by the dependency in vega-deck.gl here: https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/panel.tsx#L3

I don't know of any use case with Jest but I believe it should work fine.

**Comment by NickDarvey** [comment]
Gotcha, okay, thanks @danmarshall!
